---
  class_name: "ServicesResource"
  entry_point: "services_resource.py"
  description: "Sensor that watches Kubernetes API for new Services objects."
  trigger_types:
    -
      name: "services"
      description: "Trigger for services event dispatch."
      payload_schema:
        type: "object"
        properties:
          resource:
            type: "obj"
          name:
            type: "obj"
          labels:
            type: "obj"
          object_kind:
            type: "obj"
          namespace:
            type: "obj"
