---
  class_name: "watchAdmissionregistrationV1alpha1ExternalAdmissionHookConfigurationList"
  entry_point: "watchAdmissionregistrationV1alpha1ExternalAdmissionHookConfigurationList.py"
  description: "Sensor that watches Kubernetes API for new Externaladmissionhookconfigurations objects."
  trigger_types:
    -
      name: "externaladmissionhookconfigurations"
      description: "Trigger for externaladmissionhookconfigurations event dispatch."
      payload_schema:
        type: "object"
        properties:
          resource:
            type: "string"
          name:
            type: "string"
          labels:
            anyOf:
              - type: "object"
              - type: "string"
              - type: "null"
          object_kind:
            type: "string"
          namespace:
            type: "string"