---
  class_name: "watchExtensionsV1beta1DeploymentListForAllNamespaces"
  entry_point: "watchExtensionsV1beta1DeploymentListForAllNamespaces.py"
  description: "Sensor that watches Kubernetes API for new Deployments objects."
  trigger_types:
    -
      name: "deployments"
      description: "Trigger for deployments event dispatch."
      payload_schema:
        type: "object"
        properties:
          resource:
            type: "string"
          name:
            type: "string"
          labels:
            type: "string"
          object_kind:
            type: "string"
          namespace:
            type: "string"