---
  class_name: "watchCoreV1ConfigMapListForAllNamespaces"
  entry_point: "watchCoreV1ConfigMapListForAllNamespaces.py"
  description: "Sensor that watches Kubernetes API for new Configmaps objects."
  trigger_types:
    -
      name: "configmaps"
      description: "Trigger for configmaps event dispatch."
      payload_schema:
        type: "object"
        properties:
          resource:
            type: "string"
          name:
            type: "string"
          labels:
            type: "string"
          object_kind:
            type: "string"
          namespace:
            type: "string"