---
  class_name: "watchExtensionsV1beta1IngressListForAllNamespaces"
  entry_point: "watchExtensionsV1beta1IngressListForAllNamespaces.py"
  description: "Sensor that watches Kubernetes API for new Ingresses objects."
  trigger_types:
    -
      name: "ingresses"
      description: "Trigger for ingresses event dispatch."
      payload_schema:
        type: "object"
        properties:
          resource:
            type: "string"
          name:
            type: "string"
          labels:
            type: "object"
          object_kind:
            type: "string"
          namespace:
            type: "string"