name: createAdmissionregistrationV1alpha1ExternalAdmissionHookConfiguration
pack: kubernetes
runner_type: python-script
description: "create an ExternalAdmissionHookConfiguration"
enabled: true
entry_point: "createAdmissionregistrationV1alpha1ExternalAdmissionHookConfiguration.py"
parameters:
    config_override:
        type: object
        description: "override stackstorm config"
        secret: true
    body:
        type: object
        description: ""
        required: True
        
    pretty:
        type: string
        description: "If 'true', then the output is pretty printed."
        