name: patchAppsV1beta2NamespacedDeployment
pack: kubernetes
runner_type: python-script
description: "partially update the specified Deployment"
enabled: true
entry_point: "patchAppsV1beta2NamespacedDeployment.py"
parameters:
    config_override:
        type: object
        description: "override stackstorm config"
        secret: true
    body:
        type: object
        description: ""
        required: True
        
    name:
        type: string
        description: "name of the Deployment"
        required: True
        
    namespace:
        type: string
        description: "object name and auth scope, such as for teams and projects"
        required: True
        
    pretty:
        type: string
        description: "If 'true', then the output is pretty printed."
        