name: patchCoreV1NamespacedConfigMap
pack: kubernetes
runner_type: run-python
description: "partially update the specified ConfigMap"
enabled: true
entry_point: "patchCoreV1NamespacedConfigMap.py"
parameters:
    body:
        type: object
        description: ""
        required: True
    name:
        type: string
        description: "name of the ConfigMap"
        required: True
    namespace:
        type: string
        description: "object name and auth scope, such as for teams and projects"
        required: True
    pretty:
        type: string
        description: "If 'true', then the output is pretty printed."
