name: readExtensionsV1beta1NamespacedIngressStatus
pack: kubernetes
runner_type: run-python
description: "read status of the specified Ingress"
enabled: true
entry_point: "readExtensionsV1beta1NamespacedIngressStatus.py"
parameters:
    name:
        type: string
        description: "name of the Ingress"
        required: True
    namespace:
        type: string
        description: "object name and auth scope, such as for teams and projects"
        required: True
    pretty:
        type: string
        description: "If 'true', then the output is pretty printed."
