name: readAppsV1NamespacedDeploymentStatus
pack: kubernetes
runner_type: python-script
description: "read status of the specified Deployment"
enabled: true
entry_point: "readAppsV1NamespacedDeploymentStatus.py"
parameters:
    config_override:
        type: object
        description: "override stackstorm config"
        secret: true
    name:
        type: string
        description: "name of the Deployment"
        required: True
        
    namespace:
        type: string
        description: "object name and auth scope, such as for teams and projects"
        required: True
        
    pretty:
        type: string
        description: "If 'true', then the output is pretty printed."
        