name: replaceAdmissionregistrationV1beta1ValidatingWebhookConfiguration
pack: kubernetes
runner_type: python-script
description: "replace the specified ValidatingWebhookConfiguration"
enabled: true
entry_point: "replaceAdmissionregistrationV1beta1ValidatingWebhookConfiguration.py"
parameters:
    config_override:
        type: object
        description: "override stackstorm config"
        secret: true
    body:
        type: object
        description: ""
        required: True
        
    name:
        type: string
        description: "name of the ValidatingWebhookConfiguration"
        required: True
        
    pretty:
        type: string
        description: "If 'true', then the output is pretty printed."
        