---
name: "kubernetes_cloudformation_create"
pack: "kubernetes"
description: "Check for cloudformation events to manage from kubernetes thirdpartyresource sensor"
enabled: true

trigger:
  type: "kubernetes.thirdpartyobject"
  parameters: {}

criteria:
  trigger.resource:
    type: "contains"
    pattern: "ADDED"
  trigger.labels.type:
    type: "equals"
    pattern: "mongo"

action:
  ref: "kubernetes.cloudformation_create_chain"
  parameters:
    payload: "{{trigger}}"
