---
name: "kubernetes_mongo_delete"
pack: "kubernetes"
description: "Check for Mongo cloudformation stacks to delete using kubernetes thirdpartyresource sensor"
enabled: true

trigger:
  type: "kubernetes.thirdpartyobject"
  parameters: {}

criteria:
  trigger.resource:
    type: "contains"
    pattern: "DELETED"
  trigger.labels.type:
    type: "equals"
    pattern: "mongo"

action:
  ref: "kubernetes.mongo_delete_chain"
  parameters:
    payload: "{{trigger}}"
