---
name: "kubernetes_namespace_create"
pack: "kubernetes"
description: "Check for new namespaces"
enabled: true

trigger:
  type: "kubernetes.namespace"
  parameters: {}

criteria:
  trigger.resource:
    type: "contains"
    pattern: "ADDED"

action:
  ref: "chatops.post_message"
  parameters:
    message: "{{trigger}}"
    channel: "bitesize-andy"
