---
name: "vault_secret_create"
pack: "kubernetes"
description: "Check for new secrets"
enabled: true

trigger:
  type: "kubernetes.secret"
  parameters: {}

criteria:
  trigger.resource_type:
    type: "contains"
    pattern: "ADDED"
  trigger.object_kind:
    type: "equals"
    pattern: "Secret"
  trigger.name:
    type: "equals"
    pattern: "vault-stackstorm-mgmt"
  trigger.namespace:
    type: "equals"
    pattern: "kube-system"

action:
  ref: "bitesize.configure_vault_pack"
